name: Android CI

on:
  push:
    branches: [ main ]

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        
    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew

    - name: Clean and Build
      run: ./gradlew clean build

    # If you need to use the build artifact, you can add additional steps here to upload the artifact to GitHub, deploy it, etc.
