name: Android CI (Dockerized)

on:
  push:
    branches: [ main ]

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: mingc/android-build-box:latest

    steps:
    - uses: actions/checkout@v2

    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew

    - name: Clean and Build
      run: ./gradlew clean build
